import { Pool, types } from 'pg';
import dotenv from 'dotenv';

dotenv.config();

// pg returns bigint (20) and numeric/decimal (1700) as strings by default.
// Parse them as JS numbers so aggregations (COUNT, SUM) work correctly.
types.setTypeParser(20,   val => parseInt(val, 10));   // bigint
types.setTypeParser(1700, val => parseFloat(val));      // numeric / decimal

let pool: Pool;

export async function initializeDb() {
    pool = new Pool({
        host:     process.env.DB_HOST     || 'localhost',
        port:     Number(process.env.DB_PORT || 5432),
        database: process.env.DB_NAME     || 'dok_hr',
        user:     process.env.DB_USER     || 'dokcrm',
        password: process.env.DB_PASSWORD || '',
        max:      10,
        idleTimeoutMillis: 30000,
    });

    try {
        const client = await pool.connect();
        // Safe one-time migrations
        await client.query(`
            ALTER TABLE sites
            ADD COLUMN IF NOT EXISTS responsible_person_id INTEGER REFERENCES users(id) ON DELETE SET NULL
        `);
        await client.query(`
            ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check
        `);
        await client.query(`
            ALTER TABLE users ADD CONSTRAINT users_role_check
            CHECK (role IN ('admin','supervisor','staff','system_admin','project_manager'))
        `);
        await client.query(`
            ALTER TABLE sites ADD COLUMN IF NOT EXISTS planned_start_date DATE
        `);
        await client.query(`
            ALTER TABLE sites ADD COLUMN IF NOT EXISTS planned_end_date DATE
        `);
        await client.query(`
            ALTER TABLE sites ADD COLUMN IF NOT EXISTS planned_headcount INTEGER
        `);
        await client.query(`
            CREATE TABLE IF NOT EXISTS project_milestones (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                site_id     INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
                name        VARCHAR(200) NOT NULL,
                description VARCHAR(1000),
                due_date    DATE,
                status      VARCHAR(20) DEFAULT 'not_started'
                            CHECK (status IN ('not_started','in_progress','done')),
                sort_order  INTEGER DEFAULT 0,
                created_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
                created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        `);
        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_pm_site ON project_milestones(site_id)
        `);
        await client.query(`
            ALTER TABLE tasks ADD COLUMN IF NOT EXISTS milestone_id INTEGER
            REFERENCES project_milestones(id) ON DELETE SET NULL
        `);
        await client.query(`
            CREATE TABLE IF NOT EXISTS staff_kpi_scores (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                staff_id    INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                site_id     INTEGER NOT NULL REFERENCES sites(id) ON DELETE CASCADE,
                period      VARCHAR(20) NOT NULL,
                auto_score  NUMERIC(5,2),
                pm_score    NUMERIC(5,2),
                comments    VARCHAR(1000),
                scored_by   INTEGER REFERENCES users(id) ON DELETE SET NULL,
                created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (staff_id, site_id, period)
            )
        `);
        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_kpi_staff ON staff_kpi_scores(staff_id)
        `);
        await client.query(`
            CREATE INDEX IF NOT EXISTS idx_kpi_site ON staff_kpi_scores(site_id)
        `);
        await client.query(`
            CREATE TABLE IF NOT EXISTS milestone_stages (
                id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                name        VARCHAR(50) NOT NULL,
                sort_order  INTEGER NOT NULL DEFAULT 0,
                is_done     BOOLEAN NOT NULL DEFAULT false
            )
        `);
        // Guarded by "table is empty", not a unique constraint + ON CONFLICT — this
        // block runs on every server boot, and an unguarded INSERT would duplicate
        // the seed rows on every restart.
        await client.query(`
            INSERT INTO milestone_stages (name, sort_order, is_done)
            SELECT * FROM (VALUES
                ('To Do', 0, false),
                ('In Progress', 1, false),
                ('Done', 2, true)
            ) AS seed(name, sort_order, is_done)
            WHERE NOT EXISTS (SELECT 1 FROM milestone_stages)
        `);
        await client.query(`
            ALTER TABLE project_milestones ADD COLUMN IF NOT EXISTS stage_id INTEGER REFERENCES milestone_stages(id)
        `);
        // config.ts migrations run on every server boot, so the backfill+drop must be
        // self-guarding: once `status` is dropped, a later boot referencing pm.status
        // would error. Wrap in a check so it only ever executes once.
        await client.query(`
            DO $$
            BEGIN
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'project_milestones' AND column_name = 'status'
                ) THEN
                    UPDATE project_milestones pm
                    SET stage_id = ms.id
                    FROM milestone_stages ms
                    WHERE pm.stage_id IS NULL
                      AND ((pm.status = 'not_started' AND ms.name = 'To Do')
                        OR (pm.status = 'in_progress' AND ms.name = 'In Progress')
                        OR (pm.status = 'done' AND ms.name = 'Done'));

                    ALTER TABLE project_milestones DROP CONSTRAINT IF EXISTS project_milestones_status_check;
                    ALTER TABLE project_milestones DROP COLUMN status;
                END IF;
            END $$;
        `);
        client.release();
        console.log('Database pool created');
    } catch (err) {
        console.error('Error creating database pool', err);
        process.exit(1);
    }
}

export async function closeDb() {
    if (pool) {
        await pool.end();
        console.log('Database pool closed');
    }
}

export function getPool(): Pool {
    return pool;
}
