-- PostgreSQL Schema for DOK-HR
-- Matches Oracle schema column names exactly

CREATE TABLE sites (
  id                 INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_no            VARCHAR(64) UNIQUE NOT NULL,
  name               VARCHAR(200),
  supervisor_id      INTEGER NULL,
  task_invoice_price NUMERIC(12,2) DEFAULT 0,
  daily_target       NUMERIC DEFAULT 0,
  ot_type            VARCHAR(30) DEFAULT 'time_based' CHECK (ot_type IN ('time_based','target_based','staff_outsource')),
  service_type       VARCHAR(50),
  site_type          VARCHAR(50),
  created_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at         TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
  id                     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  epf_number             VARCHAR(64) UNIQUE NOT NULL,
  name                   VARCHAR(200) NOT NULL,
  password               VARCHAR(255) NOT NULL,
  role                   VARCHAR(20) CHECK (role IN ('admin','supervisor','staff','system_admin')) NOT NULL,
  status                 VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active','inactive')) NOT NULL,
  site_id                INTEGER NULL,
  inactivation_requested SMALLINT DEFAULT 0,
  basic_salary           NUMERIC(12,2) DEFAULT 0,
  ot_percentage          NUMERIC(6,2) DEFAULT 0,
  fix_salary             NUMERIC(12,2) DEFAULT 0,
  created_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE site_task_types (
  id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id       INTEGER NOT NULL,
  task_name     VARCHAR(200) NOT NULL,
  invoice_price NUMERIC(12,2) DEFAULT 0,
  created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_stt_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_stt_site ON site_task_types(site_id);

CREATE TABLE tasks (
  id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id          INTEGER NOT NULL,
  staff_id         INTEGER NOT NULL,
  task_description VARCHAR(1000),
  invoice_price    NUMERIC(12,2),
  ot_type          VARCHAR(20) CHECK (ot_type IN ('time_based','target_based')),
  target           NUMERIC,
  pay_unit_price   NUMERIC(12,2),
  task_date        DATE NOT NULL,
  count            NUMERIC,
  in_time          VARCHAR(8),
  out_time         VARCHAR(8),
  created_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at       TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE attendance (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id         INTEGER NOT NULL,
  staff_id        INTEGER NOT NULL,
  attendance_date DATE NOT NULL,
  in_time         VARCHAR(8),
  out_time        VARCHAR(8),
  created_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at      TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (staff_id, site_id, attendance_date)
);

CREATE TABLE custom_ot_records (
  id                   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id             VARCHAR(100) NOT NULL,
  site_no              VARCHAR(64),
  site_name            VARCHAR(200),
  staff_id             INTEGER NOT NULL,
  epf_number           VARCHAR(64),
  staff_name           VARCHAR(200) NOT NULL,
  date_from            DATE NOT NULL,
  date_to              DATE NOT NULL,
  calculation_type     VARCHAR(50),
  custom_percentage    NUMERIC(6,2),
  total_extra_hours    NUMERIC(12,4) DEFAULT 0,
  total_adjusted_hours NUMERIC(12,4) DEFAULT 0,
  ot_rate              NUMERIC(12,4) DEFAULT 0,
  total_payment        NUMERIC(14,2) DEFAULT 0,
  saved_at             TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  saved_by             INTEGER NULL
);
CREATE INDEX idx_cor_batch    ON custom_ot_records(batch_id);
CREATE INDEX idx_cor_dates    ON custom_ot_records(date_from, date_to);
CREATE INDEX idx_cor_staff    ON custom_ot_records(staff_id);
CREATE INDEX idx_cor_saved_at ON custom_ot_records(saved_at DESC);

CREATE TABLE payroll_saved_records (
  id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id        VARCHAR(100) NOT NULL,
  site_no         VARCHAR(64) NOT NULL,
  site_name       VARCHAR(200),
  staff_id        INTEGER NOT NULL,
  epf_number      VARCHAR(64),
  staff_name      VARCHAR(200) NOT NULL,
  date_from       DATE NOT NULL,
  date_to         DATE NOT NULL,
  sum_count       NUMERIC(12,2) DEFAULT 0,
  target_count    NUMERIC(12,2) DEFAULT 0,
  extra_units     NUMERIC(12,4) DEFAULT 0,
  extra_payment   NUMERIC(14,2) DEFAULT 0,
  extra_unit_rate NUMERIC(12,4) DEFAULT 0,
  saved_at        TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  saved_by        INTEGER NULL
);
CREATE INDEX idx_psr_batch    ON payroll_saved_records(batch_id);
CREATE INDEX idx_psr_dates    ON payroll_saved_records(date_from, date_to);
CREATE INDEX idx_psr_site_no  ON payroll_saved_records(site_no);
CREATE INDEX idx_psr_saved_at ON payroll_saved_records(saved_at DESC);

CREATE TABLE cost_varient (
  id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id      INTEGER NOT NULL,
  factor_key   VARCHAR(200) NOT NULL,
  factor_value VARCHAR(500),
  created_at   TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cv_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_cv_site ON cost_varient(site_id);

CREATE TABLE profit_amount (
  id                  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_id             INTEGER NOT NULL,
  site_no             VARCHAR(64),
  site_name           VARCHAR(200),
  date_from           DATE NOT NULL,
  date_to             DATE NOT NULL,
  cost_variant_amount NUMERIC(14,2) DEFAULT 0,
  salary_ot_amount    NUMERIC(14,2) DEFAULT 0,
  expense_cost        NUMERIC(14,2) DEFAULT 0,
  invoice_price       NUMERIC(14,2) DEFAULT 0,
  created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by          INTEGER NULL,
  CONSTRAINT fk_pa_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_pa_site    ON profit_amount(site_id);
CREATE INDEX idx_pa_dates   ON profit_amount(date_from, date_to);
CREATE INDEX idx_pa_created ON profit_amount(created_at DESC);

CREATE TABLE poya_days (
  id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  poya_date   DATE NOT NULL,
  description VARCHAR(200),
  created_at  TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_by  INTEGER NULL,
  CONSTRAINT uq_poya_date UNIQUE (poya_date)
);
CREATE INDEX idx_poya_date ON poya_days(poya_date);

CREATE TABLE temporary_assignments (
  id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  staff_id   INTEGER NOT NULL,
  site_id    INTEGER NOT NULL,
  start_date DATE NOT NULL,
  end_date   DATE NOT NULL,
  note       VARCHAR(255),
  created_by INTEGER NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ta_staff FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_ta_site  FOREIGN KEY (site_id)  REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_ta_staff  ON temporary_assignments(staff_id);
CREATE INDEX idx_ta_site   ON temporary_assignments(site_id);
CREATE INDEX idx_ta_dates  ON temporary_assignments(start_date, end_date);

-- FK constraints (added after both tables exist)
ALTER TABLE users ADD CONSTRAINT fk_user_site
  FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE SET NULL;
ALTER TABLE sites ADD CONSTRAINT fk_site_supervisor
  FOREIGN KEY (supervisor_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_task_site
  FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_task_staff
  FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE attendance ADD CONSTRAINT fk_att_site
  FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE;
ALTER TABLE attendance ADD CONSTRAINT fk_att_staff
  FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE CASCADE;
