-- Users Table
CREATE TABLE users (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  epf_number VARCHAR2(64) UNIQUE NOT NULL,
  name VARCHAR2(200) NOT NULL,
  password VARCHAR2(255) NOT NULL, -- Added password field
  role VARCHAR2(20) CHECK (role IN ('admin', 'supervisor', 'staff', 'system_admin')) NOT NULL,
  status VARCHAR2(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive')) NOT NULL,
  site_id NUMBER NULL,
  inactivation_requested NUMBER(1) DEFAULT 0, -- 0 for no, 1 for yes
  basic_salary NUMBER(12,2) DEFAULT 0,
  ot_percentage NUMBER(6,2) DEFAULT 0,
  fix_salary NUMBER(12,2) DEFAULT 0,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Sites Table
CREATE TABLE sites (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_no VARCHAR2(64) UNIQUE NOT NULL,
  name VARCHAR2(200),
  supervisor_id NUMBER NULL, -- FK to users(id) handled by app logic or Constraint
  task_invoice_price NUMBER(12,2) DEFAULT 0,
  daily_target NUMBER DEFAULT 0,
  ot_type VARCHAR2(30) DEFAULT 'time_based' CHECK (ot_type IN ('time_based', 'target_based', 'staff_outsource')),
  service_type VARCHAR2(50),  -- Physical | Scanning | Data entry | Insurance Policy | Staff outsource | DMS
  site_type    VARCHAR2(50),  -- Insurance | Bank | Hospital | Tele | Finance
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Site Task Types & Prices (free-form task types with invoice price per site)
CREATE TABLE site_task_types (
  id            NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_id       NUMBER NOT NULL,
  task_name     VARCHAR2(200) NOT NULL,        -- free-form task type name (e.g. Scanning, Archiving)
  invoice_price NUMBER(12,2) DEFAULT 0,        -- invoice price per unit charged to client
  created_at    TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_stt_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_stt_site ON site_task_types(site_id);

-- Tasks/Assignments Table
CREATE TABLE tasks (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_id NUMBER NOT NULL,
  staff_id NUMBER NOT NULL,
  task_description VARCHAR2(1000),
  invoice_price NUMBER(12,2),
  ot_type VARCHAR2(20) CHECK (ot_type IN ('time_based','target_based')),
  target NUMBER,
  pay_unit_price NUMBER(12,2),
  task_date DATE NOT NULL,
  count NUMBER,
  in_time VARCHAR2(8), -- Storing as HH24:MI
  out_time VARCHAR2(8),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Attendance Table (Optional/Separate as requested)
CREATE TABLE attendance (
  id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_id NUMBER NOT NULL,
  staff_id NUMBER NOT NULL,
  attendance_date DATE NOT NULL,
  in_time VARCHAR2(8),
  out_time VARCHAR2(8),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- Custom OT Records (saved history of custom OT calculations)
CREATE TABLE custom_ot_records (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  batch_id        VARCHAR2(100) NOT NULL,          -- groups all rows saved in one action
  site_no         VARCHAR2(64),
  site_name       VARCHAR2(200),
  staff_id        NUMBER NOT NULL,
  epf_number      VARCHAR2(64),
  staff_name      VARCHAR2(200) NOT NULL,
  date_from       DATE NOT NULL,
  date_to         DATE NOT NULL,
  calculation_type VARCHAR2(50),                   -- '90% Fixed' or 'Custom %'
  custom_percentage NUMBER(6,2),                   -- null for 90% Fixed rows
  total_extra_hours    NUMBER(12,4) DEFAULT 0,
  total_adjusted_hours NUMBER(12,4) DEFAULT 0,
  ot_rate              NUMBER(12,4) DEFAULT 0,
  total_payment        NUMBER(14,2) DEFAULT 0,
  saved_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
  saved_by        NUMBER NULL                      -- FK to users.id (who saved)
);

CREATE INDEX idx_cor_batch    ON custom_ot_records(batch_id);
CREATE INDEX idx_cor_dates    ON custom_ot_records(date_from, date_to);
CREATE INDEX idx_cor_staff    ON custom_ot_records(staff_id);
CREATE INDEX idx_cor_saved_at ON custom_ot_records(saved_at DESC);

-- Payroll Saved Records (saved history of target-based payroll calculations)
CREATE TABLE payroll_saved_records (
  id              NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  batch_id        VARCHAR2(100) NOT NULL,          -- groups all rows saved in one action
  site_no         VARCHAR2(64) NOT NULL,
  site_name       VARCHAR2(200),
  staff_id        NUMBER NOT NULL,
  epf_number      VARCHAR2(64),
  staff_name      VARCHAR2(200) NOT NULL,
  date_from       DATE NOT NULL,
  date_to         DATE NOT NULL,
  sum_count       NUMBER(12,2) DEFAULT 0,          -- total task count in period
  target_count    NUMBER(12,2) DEFAULT 0,          -- daily_target * DAYS_IN_PERIOD
  extra_units     NUMBER(12,4) DEFAULT 0,          -- max(0, sum_count - target_count)
  extra_payment   NUMBER(14,2) DEFAULT 0,          -- extra_units * rate
  extra_unit_rate NUMBER(12,4) DEFAULT 0,          -- rate used at time of save
  saved_at        TIMESTAMP DEFAULT SYSTIMESTAMP,
  saved_by        NUMBER NULL                      -- FK to users.id (who saved)
);

CREATE INDEX idx_psr_batch    ON payroll_saved_records(batch_id);
CREATE INDEX idx_psr_dates    ON payroll_saved_records(date_from, date_to);
CREATE INDEX idx_psr_site_no  ON payroll_saved_records(site_no);
CREATE INDEX idx_psr_saved_at ON payroll_saved_records(saved_at DESC);

-- Site Cost Variant table (key-value cost factors per site)
CREATE TABLE cost_varient (
  id           NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_id      NUMBER NOT NULL,
  factor_key   VARCHAR2(200) NOT NULL,
  factor_value VARCHAR2(500),
  created_at   TIMESTAMP DEFAULT SYSTIMESTAMP,
  CONSTRAINT fk_cv_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_cv_site ON cost_varient(site_id);

-- Invoice / Profit Amount table (monthly site-wise cost & invoice records)
CREATE TABLE profit_amount (
  id                   NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
  site_id              NUMBER NOT NULL,
  site_no              VARCHAR2(64),
  site_name            VARCHAR2(200),
  date_from            DATE NOT NULL,
  date_to              DATE NOT NULL,
  cost_variant_amount  NUMBER(14,2) DEFAULT 0,   -- sum of numeric cost_varient factors
  salary_ot_amount     NUMBER(14,2) DEFAULT 0,   -- staff salaries + OT payments
  expense_cost         NUMBER(14,2) DEFAULT 0,   -- additional expense (manual entry)
  invoice_price        NUMBER(14,2) DEFAULT 0,   -- task count × task_type invoice_price
  created_at           TIMESTAMP DEFAULT SYSTIMESTAMP,
  created_by           NUMBER NULL,
  CONSTRAINT fk_pa_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);
CREATE INDEX idx_pa_site    ON profit_amount(site_id);
CREATE INDEX idx_pa_dates   ON profit_amount(date_from, date_to);
CREATE INDEX idx_pa_created ON profit_amount(created_at DESC);

-- ─── ALTER scripts for existing databases ────────────────────────────────────
-- Run these on an existing DB to add the new columns:
--   ALTER TABLE users ADD basic_salary  NUMBER(12,2) DEFAULT 0;
--   ALTER TABLE users ADD ot_percentage NUMBER(6,2)  DEFAULT 0;
--   ALTER TABLE users ADD fix_salary    NUMBER(12,2) DEFAULT 0;
--   (profit_amount table — run full CREATE TABLE above if not exists)
--   ALTER TABLE sites ADD service_type VARCHAR2(50);
--   ALTER TABLE sites ADD site_type    VARCHAR2(50);
--   (Drop existing ot_type CHECK constraint then re-add with staff_outsource value)

-- Constraints
ALTER TABLE users ADD CONSTRAINT fk_user_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE SET NULL;
ALTER TABLE sites ADD CONSTRAINT fk_site_supervisor FOREIGN KEY (supervisor_id) REFERENCES users(id) ON DELETE SET NULL;
ALTER TABLE tasks ADD CONSTRAINT fk_task_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE;
ALTER TABLE tasks ADD CONSTRAINT fk_task_staff FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE CASCADE;
ALTER TABLE attendance ADD CONSTRAINT fk_att_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE;
ALTER TABLE attendance ADD CONSTRAINT fk_att_staff FOREIGN KEY (staff_id) REFERENCES users(id) ON DELETE CASCADE;
