ORACLE_DSN      dbi:Oracle:host=host.docker.internal;service_name=XEPDB1;port=1521
ORACLE_USER     system
ORACLE_PWD      wasath123
SCHEMA          SYSTEM

PG_VERSION      15

TABLES          users sites site_task_types tasks attendance poya_days custom_ot_records payroll_saved_records cost_varient profit_amount temporary_assignments
