-- Create site_task_types table
CREATE TABLE site_task_types (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    site_id NUMBER NOT NULL,
    task_name VARCHAR2(100) NOT NULL,
    invoice_price NUMBER(10, 2) DEFAULT 0,
    created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_site_task_site FOREIGN KEY (site_id) REFERENCES sites(id) ON DELETE CASCADE
);

-- Index for faster lookups
CREATE INDEX idx_site_task_site_id ON site_task_types(site_id);
